server:
  port: 8081
  servlet:
    context-path: /api

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: kata-backend
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}
          jwk-set-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}/protocol/openid-connect/certs

app:
  keycloak:
    admin:
      clientId: kata-id
      clientSecret: qwbMpH7xBobmU2H3kHzBvt1xSxnC42iR
    realm: kata
    serverUrl: http://localhost:9082

data:
  init:
    user:
      firstName: admin
      lastName: admin
      email: admin-kata@yopmail.com
      password: Admin123$
    roles:
      - ADMIN
      - GUEST
      - USER
