version: '3.9'

services:
  # PostgreSQL Database for Keycloak
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - local

    # Keycloak Identity and Access Management
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    command: start-dev
    restart: always
    depends_on:
      - postgres
    ports:
      - "9082:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin@1234

      KC_DB: postgres
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak

      KC_HOSTNAME: localhost
      KC_FEATURES: token-exchange,admin-fine-grained-authz
    networks:
      - local

networks:
  local:
